- hosts: all
  become: yes
  roles:
    - role: telegraf

      telegraf_outputs:
        - name: influxdb_v2
          config:
            - urls = ["http://44.231.151.241:8086"]
            - token = "abcd1234"
            - organization = "MyOrg"
            - bucket = "telegraf"

      telegraf_inputs:
        - name: cpu
          config:
            - percpu = true
            - totalcpu = true
            - collect_cpu_time = false
            - report_active = false
            - core_tags = false

        - name: disk
          config:
            - mount_points = ["/", "/tmp"]

        - name: diskio
  ## By default, telegraf will gather stats for all devices including
  ## disk partitions.
  ## Setting devices will restrict the stats to the specified devices.
  # devices = ["sda", "sdb"]
  ## Uncomment the following line if you need disk serial numbers.
  # skip_serial_number = false

# Get kernel statistics from /proc/stat
        - name: kernel
  # no configuration

# Read metrics about memory usage
        - name: mem
  # no configuration

# Get the number of processes and group them by status
        - name: processes
  # no configuration

# Read metrics about swap memory usage
        - name: swap
  # no configuration

# Read metrics about system load & uptime
        - name: system
  # no configuration
# Read metrics about network interface usage
        - name: net
  # collect data only about specific interfaces
  # interfaces = ["eth0"]

        - name: netstat
  # no configuration
        - name: interrupts
  # no configuration
        - name: linux_sysctl_fs
  # no configurati

