---
- name: Download Jenkins repo apt URL for
  apt_key: url=https://pkg.jenkins.io/debian/jenkins.io-2023.key state=present
  become: yes


- name: Install Jenkins repo for Debian
  apt_repository: repo='deb https://pkg.jenkins.io/debian-stable binary/' state=present
  become: yes

- name: Update apt cache
  apt:
    update_cache: yes


- name: Install curl
  apt: 
    name: curl
    state: present

- name: Install gnupg
  apt:
    name: gnupg
    state: present


- name: Install Java
  apt:
    name: openjdk-11-jre
    state: present

- name: Install Jenkins
  apt: 
    name: jenkins 
    state: present

- name: start jenkins service 
  service: 
    name: jenkins 
    state: started 

- name: enable jenkins to start at boot time 
  service: 
    name: jenkins 
    enabled: yes 


- name: Include config  tasks
  ansible.builtin.include_tasks: config.yml

- name: Include cli tasks
  ansible.builtin.include_tasks: cli.yml 

- name: Include plugins tasks
  ansible.builtin.include_tasks:  plugins.yml

